# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # ubuntu 20.0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn mocha

        env:
          CI: false
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} # https://github.com/AkhileshNS/heroku-deploy/issues/35#issuecomment-922254638

      - name: Deploy
        if: github.event_name == 'push'
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'express-boilerplate-ci-cd' # Must be unique in Heroku
          heroku_email: ${{secrets.PERSONAL_EMAIL}}
